---
kind: pipeline
type: docker
name: default
steps:

- name: "build and publish docker image"
  image: plugins/docker
  settings:
    registry: gitea.linuxcode.net
    repo: gitea.linuxcode.net/linuxcode/dbml-cli
    dockerfile: dockerfile
    tags: latest
    username: 
      from_secret: drone_docker_username
    password: 
      from_secret: drone_docker_password